server:
  port: 8084

spring:
  application:
    name: envio
  datasource:
    url: jdbc:mysql://localhost:3307/db_envio
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true

logging:
  level:
    root: INFO
    com.example.envio: DEBUG
  file:
    name: logs/envio.log

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true