spring.application.name=notificacion-service
spting.port=8083

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mat.navarreted@duocuc.cl
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spting.mail.properties.mail.smtp.starttls.enable=true