server:
  port: 8083

spring:
  application:
    name: notificaciones-service
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/notificaciones_db
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
springdoc:
  webmvc:
    api-docs:
      enabled: true
  hateoas:
    enabled: false